name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # ← Change this from 3.1 to 3.10 or 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -q || code=$?
        if [ "${code:-0}" = "5" ]; then
          echo "No tests collected; treating as success."
          exit 0
        else
          exit "${code:-0}"
        fi

